import type { Metadata } from "next";
import "./globals.css";
import Header from "../app/Components/Header";
import josefinsans from "../app/fonts/font";
import Footer from "../app/Components/Footer";

export const metadata: Metadata = {
  title: "blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefinsans.className} w-screen text-black bg-white overflow-x-hidden antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}